targets:
  dev:
    mode: development
    default: true
    variables:
      catalog: main_uc_dev
      repo_root: "/Workspace/Databricks_FreeEdition"
    resources:
      jobs:
        get_met_stations: {}
        ingest_update_met: {}
