targets:
  prod:
    mode: production
    default: false
    variables:
      catalog: main_uc_prod
      repo_root: "/Workspace/Databricks_FreeEdition"
    resources:
      jobs:
        get_met_stations: {}
        ingest_update_met: {}